# Generated by Django 3.2.2 on 2021-05-09 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterModelOptions(
            name='drive',
            options={'verbose_name_plural': 'Drive'},
        ),
        migrations.AlterModelOptions(
            name='fueltype',
            options={'verbose_name_plural': 'FuelType'},
        ),
        migrations.AlterModelOptions(
            name='trannsmission',
            options={'verbose_name_plural': 'Trannsmission'},
        ),
    ]
