# Generated by Django 3.2.2 on 2021-05-09 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210510_0105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='make',
            options={'verbose_name_plural': 'Make'},
        ),
    ]
