# Generated by Django 3.2.2 on 2021-05-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_make_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='engine',
            field=models.CharField(blank=True, choices=[('CC1', '700 - 1500'), ('CC2', '1500 - 2000'), ('CC3', '2000 - 3000'), ('CC4', '3000 - 4000')], help_text='Engine cc', max_length=30, null=True),
        ),
    ]
