# Generated by Django 3.2.2 on 2021-05-09 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_cars_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodytype', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'BodyType',
            },
        ),
        migrations.AddField(
            model_name='cars',
            name='ac',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='airbag',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='alloy_wheels',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='back_camera',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='cd',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='fog_light',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='keyless_entry',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='leather_seat',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='navigation',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='power_steering',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='power_window',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='rear_spoiler',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='spare_tyre',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='sunroof',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='engine',
            field=models.CharField(blank=True, help_text='Engine cc', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='body_type',
            field=models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, to='cars.bodytype'),
            preserve_default='True',
        ),
    ]
