# Generated by Django 3.2.2 on 2021-05-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20210510_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='car_main_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='cars',
            name='car_sub_image1',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='cars',
            name='car_sub_image10',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='cars',
            name='car_sub_image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='cars',
            name='car_sub_image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='cars',
            name='car_sub_image4',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='cars',
            name='car_sub_image5',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='cars',
            name='car_sub_image6',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='cars',
            name='car_sub_image7',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='cars',
            name='car_sub_image8',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='cars',
            name='car_sub_image9',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
