# Generated by Django 3.2.2 on 2021-05-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20210510_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_name',
            field=models.CharField(blank=True, help_text='Harrier 240G', max_length=50, null=True),
        ),
    ]
