# Generated by Django 3.2.2 on 2021-05-12 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_cars_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name_plural': 'cars'},
        ),
    ]
