# Generated by Django 3.1 on 2021-05-20 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_auto_20210520_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={},
        ),
    ]
