# Generated by Django 3.1 on 2021-05-27 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_auto_20210520_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spare_parts_name', models.CharField(blank=True, help_text='Rear Bumper', max_length=100, null=True)),
                ('auto_part_image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('price', models.IntegerField(blank=True, default='0', null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('condition', models.CharField(blank=True, choices=[('NEW', 'NEW'), ('USED', 'USED')], max_length=20, null=True)),
                ('make', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cars.make')),
            ],
            options={
                'verbose_name_plural': 'AutoParts',
            },
        ),
    ]
