# Generated by Django 3.1 on 2021-05-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_autoparts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoparts',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
