# Generated by Django 3.1 on 2021-05-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_auto_20210527_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoparts',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
