# Generated by Django 3.1 on 2021-05-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_autoparts_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoparts',
            name='slug',
            field=models.SlugField(blank=True, default='spareparts', null=True),
        ),
    ]
