# Generated by Django 3.1 on 2021-06-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_auto_20210527_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='AntilockBrakingSystem',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='radio',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='tv',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
    ]
