# Generated by Django 3.1 on 2021-06-02 17:31

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_auto_20210602_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='id'),
        ),
    ]
