# Generated by Django 3.1 on 2021-06-03 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0022_auto_20210603_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodytype',
            name='bodytype',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='AntilockBrakingSystem',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='ac',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='airbag',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='alloy_wheels',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='back_camera',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_main_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_name',
            field=models.CharField(blank=True, help_text='Harrier 240G', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_sub_image1',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_sub_image10',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_sub_image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_sub_image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_sub_image4',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_sub_image5',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_sub_image6',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_sub_image7',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_sub_image8',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_sub_image9',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='cd',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='fog_light',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='keyless_entry',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='leather_seat',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='mileage',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='navigation',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='power_steering',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='power_window',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='cars',
            name='radio',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='rear_spoiler',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='spare_tyre',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='sunroof',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='tv',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='drivetrain',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='make',
            name='make_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trannsmission',
            name='transmision',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
