# Generated by Django 3.1 on 2021-06-03 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0023_auto_20210603_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='engine',
            field=models.IntegerField(blank=True, help_text='Engine in CC', null=True, validators=[django.core.validators.MinValueValidator(1000)]),
        ),
    ]
