# Generated by Django 3.1 on 2021-06-03 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0025_auto_20210603_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.drive'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.make'),
        ),
    ]
