# Generated by Django 3.1 on 2021-06-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0027_auto_20210603_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='car_main_image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
