# Generated by Django 3.1 on 2021-06-03 14:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0028_auto_20210603_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoparts',
            name='auto_part_image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='autoparts',
            name='category',
            field=models.CharField(choices=[('BODY PARTS', 'BODY PARTS'), ('ENGINE & COMPONENTS', 'ENGINE & COMPONENTS'), ('CHASIS', 'CHASIS'), ('EXHAUST & COMPONENTS', 'EXHAUST & COMPONENTS'), ('EXTERIOR PARTS', 'EXTERIOR PARTS'), ('INTERIOR PARTS', 'INTERIOR PARTS'), ('LIGHTINGS', 'LIGHTINGS'), ('TIRES AND WHEELS', 'TIRES AND WHEELS'), ('SUSPENSION', 'SUSPENSION'), ('ELECTRONICS', 'ELECTRONICS'), ('BRAKE SYSTEMS', 'BRAKE SYSTEMS'), ('OTHER PARTS', 'OTHER PARTS')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='autoparts',
            name='condition',
            field=models.CharField(choices=[('NEW', 'NEW'), ('USED', 'USED')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='autoparts',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='autoparts',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.make'),
        ),
        migrations.AlterField(
            model_name='autoparts',
            name='spare_parts_name',
            field=models.CharField(help_text='Rear Bumper', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='AntilockBrakingSystem',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='ac',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='airbag',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='alloy_wheels',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='back_camera',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='body_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.bodytype'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_name',
            field=models.CharField(help_text='Harrier 240G', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_sub_image1',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_sub_image10',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_sub_image2',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_sub_image3',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_sub_image4',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_sub_image5',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_sub_image6',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_sub_image7',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_sub_image8',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_sub_image9',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='cd',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.color'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='drive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.drive'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='engine',
            field=models.IntegerField(help_text='Engine in CC', null=True, validators=[django.core.validators.MinValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='cars',
            name='fog_light',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='fueltype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.fueltype'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='keyless_entry',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='leather_seat',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.make'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='navigation',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='power_steering',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='power_window',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='radio',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='rear_spoiler',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='spare_tyre',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='sunroof',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='transmission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.trannsmission'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='tv',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=20, null=True),
        ),
    ]
