# Generated by Django 3.1 on 2021-06-03 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0029_auto_20210603_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='mileage',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000)]),
        ),
    ]
