# Generated by Django 3.1 on 2021-06-03 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0030_auto_20210603_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='mileage',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
