# Generated by Django 3.1 on 2021-06-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0031_auto_20210603_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoparts',
            name='price',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='bodytype',
            name='bodytype',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='drivetrain',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fueltype',
            name='fuel_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='make',
            name='make_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trannsmission',
            name='transmision',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
