# Generated by Django 3.1 on 2021-06-03 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0032_auto_20210603_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name_plural': 'Cars'},
        ),
        migrations.AddField(
            model_name='cars',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='autoparts',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='autoparts',
            name='price',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000)]),
        ),
    ]
