# Generated by Django 3.1 on 2021-06-04 05:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0033_auto_20210603_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='doors',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='cars',
            name='seats',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='cars',
            name='steering',
            field=models.CharField(choices=[('RIGHT', 'RIGHT'), ('LEFT', 'LEFT')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='cars',
            name='year',
            field=models.IntegerField(help_text='Manufactured Year', null=True, validators=[django.core.validators.MinValueValidator(1990)]),
        ),
    ]
