# Generated by Django 3.1 on 2021-06-04 07:45

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0034_auto_20210604_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoparts',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='autoparts',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='added_on'),
        ),
    ]
