# Generated by Django 3.1 on 2021-06-04 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0035_auto_20210604_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoparts',
            name='price',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
