# Generated by Django 3.1 on 2021-06-04 12:36

import django.core.validators
from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0037_contactinfomation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfomation',
            options={'verbose_name_plural': 'ContactInfomation'},
        ),
        migrations.AlterField(
            model_name='contactinfomation',
            name='phone_number1',
            field=phone_field.models.PhoneField(help_text='Phone Number', max_length=100, null=True, validators=[django.core.validators.RegexValidator('0\\*\\d{9}', 'Your string should start with T62* and end with six digits.')]),
        ),
        migrations.AlterField(
            model_name='contactinfomation',
            name='phone_number2',
            field=phone_field.models.PhoneField(help_text='Phone Number', max_length=10, null=True, validators=[django.core.validators.RegexValidator('0\\*\\d{9}', 'Your string should start with T62* and end with six digits.')]),
        ),
    ]
