# Generated by Django 3.1 on 2021-06-04 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0043_auto_20210604_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfomation',
            name='phone_number1',
            field=models.CharField(help_text='Phone Number', max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator('d{10}', 'Your string should be ten digits.')]),
        ),
        migrations.AlterField(
            model_name='contactinfomation',
            name='phone_number2',
            field=models.CharField(help_text='Phone Number', max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator('d{10}', 'Your string should be ten digits.')]),
        ),
    ]
