# Generated by Django 3.1 on 2021-06-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0044_auto_20210604_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfomation',
            name='phone_number1',
            field=models.CharField(help_text='Phone Number', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contactinfomation',
            name='phone_number2',
            field=models.CharField(help_text='Phone Number', max_length=10, null=True, unique=True),
        ),
    ]
