# Generated by Django 3.1 on 2021-06-06 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0046_auto_20210606_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfomation',
            name='phone_number2',
            field=models.CharField(help_text='Phone Number', max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator('^[-0-9]', 'Your string should be ten digits.')]),
        ),
    ]
