# Generated by Django 3.1 on 2021-06-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0049_contactinfomation_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoparts',
            name='category',
            field=models.CharField(choices=[('BODY PARTS', 'BODY PARTS'), ('ENGINE & COMPONENTS', 'ENGINE & COMPONENTS'), ('CHASIS', 'CHASIS'), ('EXHAUST & COMPONENTS', 'EXHAUST & COMPONENTS'), ('EXTERIOR PARTS', 'EXTERIOR PARTS'), ('INTERIOR PARTS', 'INTERIOR PARTS'), ('LIGHTINGS', 'LIGHTINGS'), ('TIRES AND WHEELS', 'TIRES AND WHEELS'), ('SUSPENSION', 'SUSPENSION'), ('ELECTRONICS', 'ELECTRONICS'), ('BRAKE SYSTEMS', 'BRAKE SYSTEMS'), ('COOLING COMPONENTS', 'COOLING COMPONENTS'), ('DOOR PARTS', 'DOOR PARTS'), ('MIRRORS', 'MIRRORS'), ('OTHER PARTS', 'OTHER PARTS')], max_length=20, null=True),
        ),
    ]
