# Generated by Django 3.1 on 2021-06-16 00:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0050_auto_20210608_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfomation',
            name='bank_account_name',
            field=models.CharField(help_text='Account name', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[-a-zA-Z]', 'Contain letters only')]),
        ),
    ]
