# Generated by Django 3.1 on 2021-06-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0051_contactinfomation_bank_account_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_line_words', models.CharField(max_length=15, null=True)),
                ('second_line_words', models.CharField(max_length=14, null=True)),
                ('third_line_words', models.CharField(max_length=10, null=True)),
                ('fourth_line_words', models.CharField(max_length=25, null=True)),
                ('banner_image1', models.ImageField(help_text='1920 x 772', null=True, upload_to='media/')),
            ],
            options={
                'verbose_name_plural': 'HomeBanner1',
            },
        ),
        migrations.CreateModel(
            name='HomeBanner2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_line_words', models.CharField(max_length=15, null=True)),
                ('second_line_words', models.CharField(max_length=14, null=True)),
                ('third_line_words', models.CharField(max_length=10, null=True)),
                ('fourth_line_words', models.CharField(max_length=25, null=True)),
                ('banner_image2', models.ImageField(help_text='1920 x 772', null=True, upload_to='media/')),
            ],
            options={
                'verbose_name_plural': 'HomeBanner2',
            },
        ),
        migrations.CreateModel(
            name='SideBanner1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_line_words', models.CharField(max_length=25, null=True)),
                ('second_line_words', models.CharField(max_length=50, null=True)),
                ('side_banner_image1', models.ImageField(help_text='315 x 375', null=True, upload_to='media/')),
            ],
            options={
                'verbose_name_plural': 'SideBanner1',
            },
        ),
        migrations.CreateModel(
            name='SideBanner2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_line_words', models.CharField(max_length=25, null=True)),
                ('second_line_words', models.CharField(max_length=50, null=True)),
                ('side_banner_image2', models.ImageField(help_text='315 x 375', null=True, upload_to='media/')),
            ],
            options={
                'verbose_name_plural': 'SideBanner2',
            },
        ),
        migrations.CreateModel(
            name='SideBanner3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_line_words', models.CharField(max_length=25, null=True)),
                ('second_line_words', models.CharField(max_length=50, null=True)),
                ('side_banner_image3', models.ImageField(help_text='315 x 375', null=True, upload_to='media/')),
            ],
            options={
                'verbose_name_plural': 'SideBanner3',
            },
        ),
    ]
